### ISSUE TITLE
[Mobile SDK] Credential Wallet - Check revocation status

### ISSUE THREAD

**Issue by rauljareno** [0xPolygonID/polygonid-flutter-sdk#45]
## Acceptance Criteria

- Given that I’m using the PolygonID SDK
- When I want to check the revocation status of a credential in the SDK
- Then I can successfully check the revocation status of the credential as result

## Task Requirements

- [x]  Follow Test Driven Development
- [x]  Implement Unit Testing
- [x]  Follow Clean Arquitecture
- [x]  Add Documentation

## Subtasks:
